/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as MathsRouteImport } from './routes/maths'
import { Route as LiteracyRouteImport } from './routes/literacy'
import { Route as HandwritingRouteImport } from './routes/handwriting'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DrawingRouteImport } from './routes/drawing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentGalleryRouteImport } from './routes/parent.gallery'
import { Route as ParentBadgesRouteImport } from './routes/parent.badges'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const MathsRoute = MathsRouteImport.update({
  id: '/maths',
  path: '/maths',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteracyRoute = LiteracyRouteImport.update({
  id: '/literacy',
  path: '/literacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HandwritingRoute = HandwritingRouteImport.update({
  id: '/handwriting',
  path: '/handwriting',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingRoute = DrawingRouteImport.update({
  id: '/drawing',
  path: '/drawing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentGalleryRoute = ParentGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ParentRoute,
} as any)
const ParentBadgesRoute = ParentBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => ParentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/drawing': typeof DrawingRoute
  '/games': typeof GamesRoute
  '/handwriting': typeof HandwritingRoute
  '/literacy': typeof LiteracyRoute
  '/maths': typeof MathsRoute
  '/parent': typeof ParentRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parent/badges': typeof ParentBadgesRoute
  '/parent/gallery': typeof ParentGalleryRoute
  '/parent/': typeof ParentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/drawing': typeof DrawingRoute
  '/games': typeof GamesRoute
  '/handwriting': typeof HandwritingRoute
  '/literacy': typeof LiteracyRoute
  '/maths': typeof MathsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parent/badges': typeof ParentBadgesRoute
  '/parent/gallery': typeof ParentGalleryRoute
  '/parent': typeof ParentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/drawing': typeof DrawingRoute
  '/games': typeof GamesRoute
  '/handwriting': typeof HandwritingRoute
  '/literacy': typeof LiteracyRoute
  '/maths': typeof MathsRoute
  '/parent': typeof ParentRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parent/badges': typeof ParentBadgesRoute
  '/parent/gallery': typeof ParentGalleryRoute
  '/parent/': typeof ParentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/drawing'
    | '/games'
    | '/handwriting'
    | '/literacy'
    | '/maths'
    | '/parent'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/parent/badges'
    | '/parent/gallery'
    | '/parent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/drawing'
    | '/games'
    | '/handwriting'
    | '/literacy'
    | '/maths'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/parent/badges'
    | '/parent/gallery'
    | '/parent'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/drawing'
    | '/games'
    | '/handwriting'
    | '/literacy'
    | '/maths'
    | '/parent'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/parent/badges'
    | '/parent/gallery'
    | '/parent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DrawingRoute: typeof DrawingRoute
  GamesRoute: typeof GamesRoute
  HandwritingRoute: typeof HandwritingRoute
  LiteracyRoute: typeof LiteracyRoute
  MathsRoute: typeof MathsRoute
  ParentRoute: typeof ParentRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maths': {
      id: '/maths'
      path: '/maths'
      fullPath: '/maths'
      preLoaderRoute: typeof MathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literacy': {
      id: '/literacy'
      path: '/literacy'
      fullPath: '/literacy'
      preLoaderRoute: typeof LiteracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwriting': {
      id: '/handwriting'
      path: '/handwriting'
      fullPath: '/handwriting'
      preLoaderRoute: typeof HandwritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawing': {
      id: '/drawing'
      path: '/drawing'
      fullPath: '/drawing'
      preLoaderRoute: typeof DrawingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/gallery': {
      id: '/parent/gallery'
      path: '/gallery'
      fullPath: '/parent/gallery'
      preLoaderRoute: typeof ParentGalleryRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/badges': {
      id: '/parent/badges'
      path: '/badges'
      fullPath: '/parent/badges'
      preLoaderRoute: typeof ParentBadgesRouteImport
      parentRoute: typeof ParentRoute
    }
  }
}

interface ParentRouteChildren {
  ParentBadgesRoute: typeof ParentBadgesRoute
  ParentGalleryRoute: typeof ParentGalleryRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentBadgesRoute: ParentBadgesRoute,
  ParentGalleryRoute: ParentGalleryRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DrawingRoute: DrawingRoute,
  GamesRoute: GamesRoute,
  HandwritingRoute: HandwritingRoute,
  LiteracyRoute: LiteracyRoute,
  MathsRoute: MathsRoute,
  ParentRoute: ParentRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
